### ISSUE TITLE
1.12.1 startup error 

### ISSUE THREAD

**Issue by hmmcrunchy** [APDevTeam/Movecraft#9]
`[22:21:41 INFO]: [Movecraft] Loading support for v1_12_R1
[22:21:41 ERROR]: Error occurred while enabling Movecraft v6.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_10_R1/util/CraftMagicNumbers
        at net.countercraft.movecraft.Movecraft.disableShadow(Movecraft.java:110) ~[?:?]
        at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:208) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-65e8124-bde2a93]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-65e8124-bde2a93]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-65e8124-bde2a93]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:380) [spigot.jar:git-Spigot-65e8124-bde2a93]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [spigot.jar:git-Spigot-65e8124-bde2a93]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-65e8124-bde2a93]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-65e8124-bde2a93]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-65e8124-bde2a93]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-65e8124-bde2a93]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-65e8124-bde2a93]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_10_R1.util.CraftMagicNumbers
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-65e8124-bde2a93]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-65e8124-bde2a93]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_05]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_05]
        ... 13 more`

**Comment by cccm5** [comment]
fixed in e88b7a30e38f5f49eff0f2937161a8066be5dadf

**Comment by hmmcrunchy** [comment]
Fab thanks cccm :)

**Comment by hmmcrunchy** [comment]
hey really sorry about this, not sure I'm being dim XD but I still have this issue, I have compat mode on true 

is there a build of e88b7a3 about I can test

**Comment by cccm5** [comment]
I've hotfixed the current release page, just re-download it and your good to go

**Comment by hmmcrunchy** [comment]
thanks once again cccm :)

**Comment by hmmcrunchy** [comment]
really sorry 

is this the one from here https://github.com/APDevTeam/Movecraft/releases/tag/7.0.0_pre-release 

with my config below 

[config.txt](https://github.com/APDevTeam/Movecraft/files/1284680/config.txt)

on spigot 1.12.1 `[13:54:08 INFO]: This server is running CraftBukkit version git-Spigot-65e8124-bde2a93 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)`

still getting the startup error

**Comment by ForsakenUniverse** [comment]
Yes, [https://github.com/APDevTeam/Movecraft/releases](release) is the correct version. Double check that your compatibility mode is true and use [pastebin.com](this) to send us the new startup error.

**Comment by hmmcrunchy** [comment]
hiya 

yes compatibility mode = true 

this error on start  


https://pastebin.com/HHuB9X1w

**Comment by Pulverizer** [comment]
@hmmcrunchy Looks like it's running fine except that something to do with shadows might not have loaded properly.

**Comment by hmmcrunchy** [comment]
I do hook in to it and get this when I try calling some items in movecraft from my plugin so thought it may not have loaded properly 

https://pastebin.com/8wjhbxc8

**Comment by keough99** [comment]
It looks like your plugin is trying to pull binaries from a file that doesn't exist

**Comment by cccm5** [comment]
I've figured out that 1.12 changes the method for disabling block lighting, so I'll have to find it again

**Comment by hmmcrunchy** [comment]
It did work ok before  so I though movecraft may not have been loading properly due to the error on start 

I'll have to have another look at what I do once all working again 

Thanks cccm

**Comment by cccm5** [comment]
Ok now I've *actually* fixed the error, the method to change a blocks solidity was changed from Block#d to Block#e

**Comment by hmmcrunchy** [comment]
Brill I'll give it a test tonight when home

**Comment by hmmcrunchy** [comment]
startup error all fixed :)
